'use client';
import { useEffect, useMemo, useState } from 'react';
import { Document, Packer, Paragraph, TextRun, HeadingLevel } from 'docx';
import { FiDownload, FiFileText, FiEye, FiPlus, FiTrash2, FiChevronLeft, FiChevronRight } from 'react-icons/fi';
type Experience={company:string;role:string;dates:string;location:string;bullets:string};
type Education={school:string;degree:string;dates:string};
type Resume={name:string;title:string;email:string;phone:string;location:string;linkedin:string;github:string;summary:string;skills:string;experience:Experience[];education:Education[];projects:string;certifications:string;template:string};
const initial:Resume={name:'',title:'',email:'',phone:'',location:'',linkedin:'',github:'',summary:'',skills:'',experience:[{company:'',role:'',dates:'',location:'',bullets:''}],education:[{school:'',degree:'',dates:''}],projects:'',certifications:'',template:'modern'};
const templates=[['modern','Modern','Clean recruiter-ready layout'],['classic','Classic','Traditional corporate resume'],['minimal','Minimal','Simple typography-first design'],['tech','Tech','Developer-focused dark accent'],['executive','Executive','Premium leadership layout'],['ats','ATS Pro','Single-column ATS optimized'],['creative','Creative','Bold modern visual hierarchy'],['academic','Academic','Research and education focused']];
function save(data:Resume){localStorage.setItem('resume-forge-data',JSON.stringify(data))}
export default function Home(){
 const [data,setData]=useState<Resume>(initial),[step,setStep]=useState(0);
 useEffect(()=>{try{const x=localStorage.getItem('resume-forge-data');if(x)setData({...initial,...JSON.parse(x)})}catch{}},[]);
 const update=(k:keyof Resume,v:any)=>{setData(d=>{const n={...d,[k]:v};save(n);return n})};
 const updateExp=(i:number,k:keyof Experience,v:string)=>setData(d=>{const e=[...d.experience];e[i]={...e[i],[k]:v};const n={...d,experience:e};save(n);return n});
 const updateEdu=(i:number,k:keyof Education,v:string)=>setData(d=>{const e=[...d.education];e[i]={...e[i],[k]:v};const n={...d,education:e};save(n);return n});
 const downloadDocx=async()=>{const children=[
  new Paragraph({text:data.name||'Your Name',heading:HeadingLevel.TITLE}),new Paragraph({children:[new TextRun({text:data.title||'Professional Title',bold:true})]}),
  new Paragraph([data.email,data.phone,data.location,data.linkedin,data.github].filter(Boolean).join(' • ')),
  new Paragraph({text:'PROFESSIONAL SUMMARY',heading:HeadingLevel.HEADING_1}),new Paragraph(data.summary||'Add your professional summary.'),
  new Paragraph({text:'EXPERIENCE',heading:HeadingLevel.HEADING_1}),...data.experience.flatMap(x=>[new Paragraph({text:x.role||'Role',heading:HeadingLevel.HEADING_2}),new Paragraph((x.company||'Company')+(x.dates?' • '+x.dates:'')),...x.bullets.split('\n').filter(Boolean).map(b=>new Paragraph({text:b,bullet:{level:0}}))]),
  new Paragraph({text:'EDUCATION',heading:HeadingLevel.HEADING_1}),...data.education.flatMap(x=>[new Paragraph({text:x.degree||'Degree',heading:HeadingLevel.HEADING_2}),new Paragraph((x.school||'University')+(x.dates?' • '+x.dates:''))]),
  new Paragraph({text:'SKILLS',heading:HeadingLevel.HEADING_1}),new Paragraph(data.skills),new Paragraph({text:'PROJECTS',heading:HeadingLevel.HEADING_1}),new Paragraph(data.projects),new Paragraph({text:'CERTIFICATIONS',heading:HeadingLevel.HEADING_1}),new Paragraph(data.certifications)
 ];const blob=await Packer.toBlob(new Document({sections:[{children}]}));const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='resume.docx';a.click();URL.revokeObjectURL(a.href)};
 const filled=useMemo(()=>[data.name,data.title,data.email,data.summary,data.skills].filter(Boolean).length,[data]);
 return <main className="app"><header className="topbar"><div className="logo">Resume<span>Forge</span></div><div className="progress"><b>{step+1}</b> / 4</div><div className="top-actions"><button onClick={()=>window.print()}><FiFileText/> PDF</button><button className="primary" onClick={downloadDocx}><FiDownload/> Word</button></div></header>
 <div className="workspace"><aside className="editor"><div className="steps">{['Details','Experience','Education','Extras'].map((x,i)=><button className={step===i?'active':''} onClick={()=>setStep(i)} key={x}><span>0{i+1}</span>{x}</button>)}</div>
 {step===0&&<><Section title="Personal information"><Field label="Full name" value={data.name} onChange={v=>update('name',v)} placeholder="e.g. Beesetti Narsingarao"/><Field label="Professional title" value={data.title} onChange={v=>update('title',v)} placeholder="e.g. MuleSoft Developer"/></Section><Section title="Contact"><div className="two"><Field label="Email" value={data.email} onChange={v=>update('email',v)}/><Field label="Phone" value={data.phone} onChange={v=>update('phone',v)}/></div><div className="two"><Field label="Location" value={data.location} onChange={v=>update('location',v)}/><Field label="LinkedIn" value={data.linkedin} onChange={v=>update('linkedin',v)}/></div><Field label="GitHub / Portfolio" value={data.github} onChange={v=>update('github',v)}/></Section><Section title="Summary"><TextArea value={data.summary} onChange={v=>update('summary',v)} placeholder="Write a concise professional summary..."/></Section></>}
 {step===1&&<Section title="Work experience">{data.experience.map((x,i)=><div className="repeat" key={i}><div className="repeat-head"><b>Experience {i+1}</b>{data.experience.length>1&&<button onClick={()=>update('experience',data.experience.filter((_,j)=>j!==i))}><FiTrash2/></button>}</div><div className="two"><Field label="Role" value={x.role} onChange={v=>updateExp(i,'role',v)}/><Field label="Company" value={x.company} onChange={v=>updateExp(i,'company',v)}/></div><div className="two"><Field label="Dates" value={x.dates} onChange={v=>updateExp(i,'dates',v)}/><Field label="Location" value={x.location} onChange={v=>updateExp(i,'location',v)}/></div><TextArea label="Achievements / responsibilities" value={x.bullets} onChange={v=>updateExp(i,'bullets',v)} placeholder="One achievement per line"/></div>)}<button className="add" onClick={()=>update('experience',[...data.experience,{company:'',role:'',dates:'',location:'',bullets:''}])}><FiPlus/> Add experience</button></Section>}
 {step===2&&<Section title="Education">{data.education.map((x,i)=><div className="repeat" key={i}><div className="repeat-head"><b>Education {i+1}</b>{data.education.length>1&&<button onClick={()=>update('education',data.education.filter((_,j)=>j!==i))}><FiTrash2/></button>}</div><Field label="Degree" value={x.degree} onChange={v=>updateEdu(i,'degree',v)}/><div className="two"><Field label="School / University" value={x.school} onChange={v=>updateEdu(i,'school',v)}/><Field label="Dates" value={x.dates} onChange={v=>updateEdu(i,'dates',v)}/></div></div>)}<button className="add" onClick={()=>update('education',[...data.education,{school:'',degree:'',dates:''}])}><FiPlus/> Add education</button></Section>}
 {step===3&&<><Section title="Skills"><TextArea value={data.skills} onChange={v=>update('skills',v)} placeholder="MuleSoft, DataWeave, RAML, GitHub Actions, SQL..."/></Section><Section title="Projects"><TextArea value={data.projects} onChange={v=>update('projects',v)} placeholder="Projects, achievements, measurable impact..."/></Section><Section title="Certifications"><TextArea value={data.certifications} onChange={v=>update('certifications',v)} placeholder="Certification name — issuer — year"/></Section><Section title="Template"><div className="templates">{templates.map(([id,name,desc])=><button className={data.template===id?'selected':''} onClick={()=>update('template',id)} key={id}><strong>{name}</strong><small>{desc}</small></button>)}</div></Section></>}
 <div className="editor-nav"><button disabled={step===0} onClick={()=>setStep(step-1)}><FiChevronLeft/> Back</button><button disabled={step===3} className="primary" onClick={()=>setStep(step+1)}>Next <FiChevronRight/></button></div></aside>
 <section className="preview"><div className="preview-head"><span><FiEye/> Live preview</span><small>{filled}/5 key fields completed</small></div><div className="paper-wrap"><article className={'resume-page '+data.template}><h1>{data.name||'Your Name'}</h1><h2>{data.title||'Professional Title'}</h2><div className="contact-line">{[data.email,data.phone,data.location,data.linkedin,data.github].filter(Boolean).join('  •  ')||'email • phone • location • LinkedIn'}</div><ResumeSection title="PROFILE"><p>{data.summary||'Your professional summary will appear here. Describe your experience, strengths and the value you bring.'}</p></ResumeSection><ResumeSection title="EXPERIENCE">{data.experience.map((x,i)=><div className="r-exp" key={i}><div><b>{x.role||'Role'}</b><span>{x.company||'Company'} {x.dates&&'• '+x.dates}</span></div><p>{x.bullets||'Add responsibilities and measurable achievements.'}</p></div>)}</ResumeSection><ResumeSection title="EDUCATION">{data.education.map((x,i)=><div className="r-exp" key={i}><div><b>{x.degree||'Degree'}</b><span>{x.school||'University'} {x.dates&&'• '+x.dates}</span></div></div>)}</ResumeSection>{data.skills&&<ResumeSection title="SKILLS"><p>{data.skills}</p></ResumeSection>}{data.projects&&<ResumeSection title="PROJECTS"><p>{data.projects}</p></ResumeSection>}{data.certifications&&<ResumeSection title="CERTIFICATIONS"><p>{data.certifications}</p></ResumeSection>}</article></div></section></div></main>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="form-section"><h3>{title}</h3>{children}</section>}
function Field({label,value,onChange,placeholder}:{label?:string;value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="field">{label&&<span>{label}</span>}<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function TextArea({label,value,onChange,placeholder}:{label?:string;value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="field">{label&&<span>{label}</span>}<textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function ResumeSection({title,children}:{title:string;children:React.ReactNode}){return <section className="r-section"><h3>{title}</h3>{children}</section>}
