'use client';
import { useEffect,useState } from 'react';
import { motion } from 'framer-motion';
import { FiArrowUpRight,FiGithub,FiLinkedin,FiMail,FiMenu,FiMoon,FiSun,FiX } from 'react-icons/fi';
const navigation=[['01','About','#about'],['02','Experience','#experience'],['03','Projects','#projects'],['04','Contact','#contact']];
const skills=['Mule 4','Anypoint Platform','DataWeave','RAML','APIKit','CloudHub','IBM MQ','IBM MFT','DataPower','Runtime Manager','Dynatrace','ELK','GitHub Actions','Postman','SQL','MUnit'];
const projects=[['01','MuleForge','Open-source Mule 4 generator for RAML, Mule XML, Maven and connector scaffolding.','https://github.com/Narsing-s/muleforge'],['02','MuleSoft AI Engineering Copilot','AI-assisted MuleSoft engineering, DataWeave and integration workflows.','https://github.com/Narsing-s/mulesoft-ai-engineering-copilot'],['03','Global Messenger','Open-source real-time communication platform designed for self-hosting and cross-device use.','https://github.com/Narsing-s/global-messanger']];
export default function Home(){
 const[dark,setDark]=useState(true),[menu,setMenu]=useState(false),[loaded,setLoaded]=useState(false);
 useEffect(()=>{const t=window.setTimeout(()=>setLoaded(true),550);return()=>window.clearTimeout(t)},[]);
 const profile={role:'MuleSoft Support',focus:'reliability',experience:'4+ years',apis:'600+',mftTransfers:'1000+',incidentLevel:'L2 / L3',status:'operational'};
 return <main className={dark?'site dark':'site'}>
 {!loaded&&<div className="loader"><div className="loader-mark">N</div><span>NARSING</span></div>}
 <header className="header"><motion.a href="#home" className="brand" initial={{opacity:0,x:-20}} animate={{opacity:1,x:0}}>N<span>.</span></motion.a>
 <nav className="desktop-nav">{navigation.map(([num,name,href],i)=><motion.a key={name} href={href} initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} transition={{delay:i*.08}}><b>{num}.</b> {name}</motion.a>)}</nav>
 <div className="header-actions"><button aria-label="Toggle theme" onClick={()=>setDark(!dark)}>{dark?<FiSun/>:<FiMoon/>}</button><button className="mobile-menu-button" aria-label="Menu" onClick={()=>setMenu(!menu)}>{menu?<FiX/>:<FiMenu/>}</button></div></header>
 {menu&&<div className="mobile-menu">{navigation.map(([num,name,href])=><a key={name} href={href} onClick={()=>setMenu(false)}><b>{num}.</b> {name}</a>)}<button onClick={()=>setDark(!dark)}>{dark?'Light mode':'Dark mode'}</button></div>}
 <aside className="side side-left"><a href="https://github.com/Narsing-s" target="_blank" rel="noreferrer"><FiGithub/></a><a href="https://www.linkedin.com/in/beesetti-narsingarao-170549226" target="_blank" rel="noreferrer"><FiLinkedin/></a><i/></aside>
 <aside className="side side-right"><a href="mailto:narsingbeesetti06@gmail.com">narsingbeesetti06@gmail.com</a><i/></aside>
 <section id="home" className="hero"><div className="hero-copy"><motion.p className="kicker" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}>MULESOFT · INTEGRATION · PRODUCTION SUPPORT</motion.p><motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}}>Narsing<br/><em>Beesetti</em></motion.h1><motion.p className="hero-role" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}>MuleSoft Developer · Integration Specialist · Production Support</motion.p><p className="hero-text">I keep enterprise integrations reliable — supporting critical APIs, messaging, transformations, deployments and production incidents across MuleSoft and IBM integration platforms.</p><div className="actions"><a className="primary" href="#about">Explore profile <FiArrowUpRight/></a><a href="https://github.com/Narsing-s" target="_blank" rel="noreferrer">GitHub <FiGithub/></a></div></div>
 <motion.div className="hero-visual" initial={{opacity:0,x:35}} animate={{opacity:1,x:0}} transition={{duration:.7}}><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="code-card"><div className="window-bar"><span/><span/><span/><small>production.json</small></div><pre>{JSON.stringify(profile,null,2)}</pre></div></motion.div></section>
 <div className="stats">{[['4+','Years IT experience'],['3+','Years MuleSoft'],['600+','APIs supported'],['1000+','MFT transfers']].map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
 <section id="about" className="section"><div className="section-number">01 — ABOUT</div><h2>Support-first engineering for <em>critical integrations.</em></h2><div className="about-grid"><div><p>My work focuses on availability, performance and recoverability of enterprise APIs and integrations. I handle L2/L3 production incidents, troubleshoot data transformation, connectivity and authentication issues, and coordinate resolution across application and platform teams.</p><p>I work across MuleSoft, SAP, EDI, Salesforce, IBM MQ/MFT and on-premise/cloud systems, using observability and CI/CD tooling to move from alert to root cause to validated recovery.</p></div><div className="skill-panel"><span className="panel-title">CORE TOOLKIT</span><div className="chips">{skills.map(skill=><span key={skill}>{skill}</span>)}</div></div></div></section>
 <section id="experience" className="section"><div className="section-number">02 — EXPERIENCE</div><h2>Keeping production <em>moving.</em></h2><div className="experience-list"><article><span className="exp-index">01</span><div><p className="exp-meta">ENTERPRISE PHARMACEUTICAL ENVIRONMENT · L2/L3</p><h3>MuleSoft Production Support & Integration</h3><p>Monitor critical APIs with Anypoint Monitoring, Runtime Manager, Dynatrace and ELK; investigate P1/P2 incidents, validate deployments, perform RCA, support certificates and production credentials, and coordinate outage recovery.</p></div></article><article><span className="exp-index">02</span><div><p className="exp-meta">MULESOFT · IBM WEBSPHERE · MESSAGING</p><h3>Integration Reliability & Operations</h3><p>Support API and file-transfer flows across SAP, EDI, Salesforce and custom systems. Troubleshoot IBM MQ/MFT, DataPower, transformations, connectivity and authentication while maintaining operational continuity.</p></div></article></div></section>
 <section id="projects" className="section"><div className="section-number">03 — PROJECTS</div><h2>Builds outside <em>production.</em></h2><div className="project-grid">{projects.map(([num,title,description,href])=><motion.a key={title} href={href} target="_blank" rel="noreferrer" className="project-card" whileHover={{y:-8}}><div className="project-top"><span>{num}</span><FiArrowUpRight/></div><div><h3>{title}</h3><p>{description}</p></div><span className="project-link">VIEW REPOSITORY</span></motion.a>)}</div></section>
 <section id="contact" className="section contact"><div className="section-number">04 — CONTACT</div><h2>Let’s build something <em>reliable.</em></h2><p>Open to MuleSoft, integration engineering and production-support opportunities.</p><div className="contact-links"><a href="mailto:narsingbeesetti06@gmail.com"><FiMail/> Email</a><a href="https://www.linkedin.com/in/beesetti-narsingarao-170549226" target="_blank" rel="noreferrer"><FiLinkedin/> LinkedIn</a><a href="https://github.com/Narsing-s" target="_blank" rel="noreferrer"><FiGithub/> GitHub</a></div></section>
 <footer><span>© 2026 Narsing Beesetti</span><span>Designed for integration reliability.</span></footer></main>;
}