'use client';
import {motion} from 'framer-motion';
import {FiGithub,FiLinkedin,FiMail,FiArrowUpRight,FiMoon,FiSun} from 'react-icons/fi';
import {useState} from 'react';

const projects=[['MuleForge','Open-source Mule 4 project generator for RAML, Mule XML, Maven and connector scaffolding.','https://github.com/Narsing-s/muleforge'],['MuleSoft AI Engineering Copilot','AI-assisted MuleSoft engineering, DataWeave and integration workflows.','https://github.com/Narsing-s/mulesoft-ai-engineering-copilot'],['Global Messenger','Open-source real-time communication platform focused on self-hosting and cross-device access.','https://github.com/Narsing-s/global-messanger']];
const skills=['Mule 4','Anypoint Platform','DataWeave','RAML','APIKit','CloudHub','IBM MQ','IBM MFT','DataPower','Runtime Manager','Dynatrace','ELK','GitHub Actions','Postman','SQL','MUnit'];
export default function Home(){const[dark,setDark]=useState(true);return <main className={dark?'site dark':'site'}>
<header className="header"><a className="logo" href="#home">NARSING<span>.</span></a><nav><a href="#about">About</a><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#contact">Contact</a></nav><button className="theme" onClick={()=>setDark(!dark)}>{dark?<FiSun/>:<FiMoon/>}</button></header>
<section id="home" className="hero"><div className="hero-copy"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="eyebrow">MULESOFT · INTEGRATION · PRODUCTION SUPPORT</motion.div><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.08}}>Building integrations that stay <em>reliable.</em></motion.h1><p>I’m Narsing Beesetti, a MuleSoft Developer and Integration Specialist focused on L2/L3 production support, enterprise APIs, messaging, observability and incident resolution.</p><div className="actions"><a className="primary" href="#contact">Let’s connect <FiArrowUpRight/></a><a href="https://github.com/Narsing-s" target="_blank">GitHub <FiGithub/></a></div></div><motion.div className="hero-card" initial={{opacity:0,x:30}} animate={{opacity:1,x:0}}><div className="dots">● ● ●</div><pre>{`{\n  name: "Narsing Beesetti",\n  focus: "MuleSoft + Integration",\n  role: "Production Support",\n  experience: "4+ years",\n  apis: "600+",\n  mft: "1000+",\n  status: "available"\n}`}</pre></motion.div></section>
<div className="metrics"><div><b>4+</b><span>Years IT</span></div><div><b>3+</b><span>Years MuleSoft</span></div><div><b>600+</b><span>APIs supported</span></div><div><b>1000+</b><span>MFT transfers</span></div></div>
<section id="about" className="section"><div className="label">01 — ABOUT</div><h2>Support-first engineering.</h2><div className="split"><p>My work centers on keeping critical enterprise integrations available, observable and recoverable. I troubleshoot API failures, transformations, connectivity, authentication, messaging and deployment issues while coordinating incident resolution across teams.</p><div className="chips">{skills.map(s=><span key={s}>{s}</span>)}</div></div></section>
<section id="experience" className="section"><div className="label">02 — EXPERIENCE</div><h2>Production operations with an integration mindset.</h2><div className="timeline"><article><span>01</span><div><h3>MuleSoft Production Support / Integration</h3><p>Enterprise pharmaceutical environment · L2/L3</p><p>Monitor critical APIs, investigate P1/P2 incidents, analyze logs and correlation IDs, validate deployments, perform RCA, support certificates/passwords and coordinate with application/platform teams.</p></div></article><article><span>02</span><div><h3>Enterprise Integration Reliability</h3><p>MuleSoft · IBM WebSphere · Messaging · Observability</p><p>Anypoint Monitoring, Runtime Manager, Dynatrace, ELK, IBM MQ/MFT, Git/CI-CD, Postman and SQL for diagnosis and operational support.</p></div></article></div></section>
<section id="projects" className="section"><div className="label">03 — PROJECTS</div><h2>Things I build beyond production.</h2><div className="project-grid">{projects.map((p,i)=><motion.a whileHover={{y:-7}} className="project" href={p[2]} target="_blank" key={p[0]}><small>0{i+1}</small><h3>{p[0]} <FiArrowUpRight/></h3><p>{p[1]}</p><span>View repository</span></motion.a>)}</div></section>
<section id="contact" className="section contact"><div className="label">04 — CONTACT</div><h2>Let’s work on reliable integrations.</h2><p>Open to MuleSoft, integration and production-support opportunities.</p><div className="contact-links"><a href="mailto:narsingbeesetti06@gmail.com"><FiMail/> narsingbeesetti06@gmail.com</a><a href="https://www.linkedin.com/in/beesetti-narsingarao-170549226" target="_blank"><FiLinkedin/> LinkedIn</a><a href="https://github.com/Narsing-s" target="_blank"><FiGithub/> GitHub</a></div></section>
<footer>© 2026 Narsing Beesetti <span>Built for reliability.</span></footer></main>}